class AppStrings {
  static String appname = "doctorsapp",
      BestDocApp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome Back!",
      welcome = "Welcome",
      weAreExcited = "We are excited to have you back",
      signupnow =
          "Sign Up now and start exploring all that our app has to offer",
      email = "Email",
      emailHint = "Enter your email",
      password = "Password",
      passwordHint = "Enter your password here",
      fullname = "Full Name",
      fullnameHint = "Enter your name here",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password?",
      login = "Login",
      signup = "Sign Up",
      alreadyHaveAccount = "Already have an Account?",
      dontHaveAccount = "Don't Have an Account?",
      search = "Search Doctor",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidney = "Kidney";
}
